### ISSUE TITLE
New ORDER NOTIFICATIONS fail to save to the ui.

### ISSUE THREAD

**Issue by FredK19** [CommerceRack/backend#28]
#### TICKET SUMMARY #####

ISSUE:	The system does not save/ acknowledge when an ORDER notification has
been configured.

ACCT:  Testing done in account LAWRENCEM

SERVER:  Naboo

MVC release:  201408.g

EXAMPLE NOTIFICATION:  ORDER.MOVE.COMPLETED

EXAMPLE ORDER:	2014-08-1085

STEPS TO REPRODUCE:
Setup >> Notifications >>  Add New:
Event:	ORDER.MOVE.COMPLETED
Method: EMAIL
Email(s): fredk@zoovy.com
Click  [Save New Notification]

RESULTS:   
The new notification does NOT appear under the ORDERS tab (or any other).
Multiple API  Requests and Responses are generated by clicking the [Save New
Notification]  button.	 See below.

REQUEST BODY:
{"_uuid":1022,"_session":"90cb262e6a0e7a581f2983c154ef9aca","_cmd":"pipeline","@cmds":[{"_cmd":"adminConfigMacro","@updates":[],"_uuid":1021}],"_clientid":"admin","_domain":"nyciwear.com","_userid":"support/fredk@nyciwear","_deviceid":"nLYpTvYfJnQmle987FZj6Uo17PnvRnnh","_authtoken":"1|XYIe5Y4XEXm7gXiLsngGB7JU|9977d8f7e202c9cb79da82255684b2fca0ae0dff","_version":"201405"}

RESPONSE BODY:
{"_rcmd":"pipeline","_uuid":1022,"@rcmds":[{"_rcmd":"adminConfigMacro","_rtag":null,"_uuid":1021}]}

============================================================

REQUEST BODY:
webservice_latency~ms~duration~205~api=ListFolders,farm=1602,colo=bf1,mlcluster=n6b,yid=fredkaufmann19,ymreqid=11ce8236-7199-786f-0108-6dSEQN010000

RESPONSE BODY:
No Response Body

============================================================

REQUEST BODY:
{"_uuid":1024,"_session":"90cb262e6a0e7a581f2983c154ef9aca","_cmd":"pipeline","@cmds":[{"_cmd":"adminMessagesList","msgid":0,"_uuid":1020},{"_cmd":"adminConfigDetail","notifications":1,"_uuid":1023}],"_clientid":"admin","_domain":"nyciwear.com","_userid":"support/fredk@nyciwear","_deviceid":"nLYpTvYfJnQmle987FZj6Uo17PnvRnnh","_authtoken":"1|XYIe5Y4XEXm7gXiLsngGB7JU|9977d8f7e202c9cb79da82255684b2fca0ae0dff","_version":"201405"}

RESPONSE BODY:
{"_rcmd":"pipeline","_uuid":1024,"@rcmds":[{"_rcmd":"adminMessagesList","_rtag":null,"_uuid":1020,"@MSGS":[]},{"_rcmd":"adminConfigDetail","@NOTIFICATIONS":[{"@VERBS":[{"verb":"task"}],"event":"ALERT"},{"@VERBS":[{"verb":"task"}],"event":"ALERT.INV.RESTOCK"},{"@VERBS":[{"verb":"task"}],"event":"APIERR"},{"@VERBS":[{"verb":"task"}],"event":"CUSTOMER.ORDER.CANCEL"},{"@VERBS":[{"verb":"task"}],"event":"ENQUIRY"},{"@VERBS":[{"verb":"task"}],"event":"ERROR"},{"@VERBS":[{"verb":"task"}],"event":"INV.NAVCAT.FAIL"},{"@VERBS":[{"verb":"task"}],"event":"INV.NAVCAT.HIDE"},{"@VERBS":[{"verb":"task"}],"event":"INV.NAVCAT.SHOW"}],"_rtag":null,"_uuid":1023}]}

**Comment by andrewtodd3** [comment]
This issue has been resolved
