### ISSUE TITLE
Typo in the %ORDERNOTES% system macro code

### ISSUE THREAD

**Issue by LarryM-CR** [CommerceRack/backend#30]
TICKET SUMMARY

ISSUE: Typo in the %ORDERNOTES% system macro is causing order notes to not
print on invoices.

ACCOUNT: gogoods (happening on others too)

SERVER: naboo

MVC RELEASE: 201408.g

STEPS TO REPRODUCE:
1) Setup > Email Config and Messages > Settings > System Macros > %ORDERNOTES%
2) Code displayed is; div data-tlc="bind $var '.%ORDER.%want.order_notes';
apply --append;"
3) Typo is the percent sign before 'want.' - Code should be; div
data-tlc="bind $var '.%ORDER.want.order_notes'; apply --append;"

TROUBLESHOOTING:
1) Cloned %ORDERNOTES% to custom macro and removed the percent sign from
'%want.' to make it; div data-tlc="bind $var '.%ORDER.want.order_notes'; apply
--append;"
2) Added in cloned macro to the invoice print code and it printed the order
notes properly.

NOTES: Typo exists on multiple servers.

**Comment by michaelchance** [comment]
Found and committed the fix, thanks!
