### ISSUE TITLE
Disallow PO Box Addresses setting is not saving in the Shipping interface.

### ISSUE THREAD

**Issue by FredK19** [CommerceRack/backend#40]
#### TICKET SUMMARY #####

ISSUE:	 There is no way to save the Do not allow checkout for addresses that
appear to be P.O. Boxes configuration in the Shipping interface.

ACCT:  Rittersgifts

SERVER:  Endor5

MVC release:  201408.g

STEPS TO REPRODUCE:
Setup >> Shipping >> Global / General:
Change the toggle switch for,  Do not allow checkout for addresses that appear
to be P.O. Boxes   to On,  click Save Changes.

The setting appears to change, but exiting the Shipping ui , and returning
shows that the setting is still set to Off.

API WHEN CHANGING TOGGLE TO ON:
REQUEST BODY:
[{"id":"882","ext":{"timestamp":1416249542211,"host":"us-mg6.mail.yahoo.com"},"channel":"/meta/connect","connectionType":"long-polling","clientId":"pr57.9561914162445808725783206909.pDLA99AlfL.BYQX31zPzz1d_DgYv3EuKWT18qMk-"}]

RESPONSE BODY:
[{"channel":"/meta/connect", "timestamp":"2014-11-17T18:39:12.436177",
"successful":true,
"clientId":"pr57.9561914162445808725783206909.pDLA99AlfL.BYQX31zPzz1d_DgYv3EuKWT18qMk-",
"id":"882", "advice": {"interval":7220}}]

API WHEN CLICKING SAVE CHANGES:
REQUEST BODY:
{"_uuid":1025,"_session":"1ac5bb02cf4676630cbc41e63400a792","_cmd":"pipeline","@cmds":[{"@updates":["SHIPPING/CONFIG?ship_int_risk=NONE&ship_origin_zip=19606&ship_latency=1&ship_cutoff=14%3A00&chkout_deny_ship_po=1&country=&type=&match="],"_cmd":"adminConfigMacro","_uuid":1023},{"shipping":true,"_cmd":"adminConfigDetail","_uuid":1024}],"_clientid":"admin","_domain":"teacupgallery.com","_userid":"support/fredk@rittersgifts","_deviceid":"PtmFpAQQR6XO1B5fOouOLM5sN61Tt6YY","_authtoken":"1|J5BN4B5OfvE5RRiDl6VLEFl9|16240c69b24f3caaed045f8d46d472a180e3d763","_version":"201405"}

RESPONSES BODY:
{"_rcmd":"pipeline","_uuid":1025,"@rcmds":[{"_rcmd":"adminConfigMacro","_rtag":null,"_uuid":1023},{"ship_int_risk":"NONE","%SHIPPING":{"@BLACKLIST":["NG","SOX"],"@BANNED":[{"created":"1279645864","match":"MAIRIAC@WEBTV.NET","type":"EMAIL"},{"created":"1301927060","match":"LIWHIT50@YAHOO.COM","type":"EMAIL"}]},"_uuid":1024,"primary_shipper":"UPS","ship_latency":"1","_rcmd":"adminConfigDetail","_rtag":null,"ship_origin_zip":"19606","ship_cutoff":"14:00"}]}

**Comment by michaelchance** [comment]
As far as I can tell, this is a back end issue.  I'll forward this to Brian.

**Comment by michaelchance** [comment]
@brianhorakh Doesn't appear that "chkout_deny_ship_po=1" in the macro is saving- I had a quick look at the back end code but nothing stood out, all looked right to me.
