### ISSUE TITLE
Creating custom macros allow more than 15 characters in the Macro ID field.

### ISSUE THREAD

**Issue by LarryM-CR** [CommerceRack/backend#48]
ISSUE: The field MACROID in the BLAST_MACROS database table is limited to 15 characters. However when setting up a new custom macro, the UI allows the user to enter more than 15 characters. This causes a truncated MACROID that cannot be removed via the UI.

SERVER: Naboo

ACCT: gogoods

MVC release: 201411.b

STEPS TO REPRODUCE:
Setup > Email Config and Messages > Custom Macros > [Add Macro] > Macro ID field allows more than 15 characters to be entered.

NOTE: Merchant created a long macro accidentally as there is no character limit warning but was unable to delete it via the UI. I removed it manually from the BLAST_MACROS table.

**Comment by pterolex** [comment]
Fixed with https://github.com/CommerceRack/anycommerce/commit/cd7f9518c76cdc8bac04589e2cccfc163f1f4ad7?w=1
