### ISSUE TITLE
Unable to save changes in Organization Manager

### ISSUE THREAD

**Issue by FredK19** [CommerceRack/backend#51]
#### TICKET SUMMARY #####

ISSUE:	Unable to save settings in the Organizations ui.

Acct:  Gogoods

SERVER:  2939111

MVC release:  201411.b

EXAMPLE ORGANIZATION:  422357

EXAMPLE COMPANY:  Victory Supply, Inc.

STEPS TO REPRODUCE:
Utilities >> Organization Manager >> 422357  [edit].
Switch the Allow Resale/Tax Exempt toggle to  ON.

First problem:	The Save Change button is not activated, so there is no way to
save the edit.

In order to activate the Save Changes button, I altered the Schedule drop down
from RS to None, than back to RS.  This allows the Save Changes button to be
clicked.

But clicking the Save Changes button does not actually Save the configuration
edit.

Switching the  Allow Resale/Tax Exempt toggle to ON does not generate a Request
or Response.

NOTES:	 I am able to change which Schedule is configured in the drop down, as
that configuration change saves properly.
When the Schedule is changed AND the Tax Exempt toggle is turned to on, the
save button still displays as  [Save 1 Changes], when it should display [Save 2
Changes]

BONUS NOTES:  When changing the Schedule configuration to confirm that edit
saved, I noticed that even after the configuration has been processed, the Save
Changes button still displays as illuminated, suggesting that there is still a
change to be saved, although there is not.

**Comment by michaelchance** [comment]
Fixed with commit https://github.com/CommerceRack/anycommerce/commit/0b35e1f46478080ee959c67ffd71f3c0a811e8de
