### ISSUE TITLE
Flexedit Manager not saving updates in 201501.a

### ISSUE THREAD

**Issue by FredK19** [CommerceRack/backend#57]
#### TICKET SUMMARY #####

ISSUE:   Configuration changes are not saving in the Flexedit Manager in release 201501.a

ACCT:  Gogoods

SERVER:  Naboo

MVC release:  201501.a

STEPS TO REPRODUCE:
Utilities >> Manage Flexedit Fields:  Attempt to add a field from the Popular Attributes list to the Enabled Attributes list.  The field appears to be added, but leaving and returning to the ui shows the change was not saved.
Editing an attribute already in the Enabled Attributes list is also not saving.

REQUEST BODY:
Whether attempting to move an attribute to the Enabled Attributes list, or attempting to save edits to existing Enabled Attributes by clicking the Save Attributes button, there is no Request Body generated.

NOTES:  Configuration changes appear to save successfully in the 201408 release.

**Comment by michaelchance** [comment]
In the most recent version of 201501, the flexedit manager has been replaced by a simple text box with JSON input.
