### ISSUE TITLE
Unable to merge order onto existing Customer Account in online Orders ui.

### ISSUE THREAD

**Issue by FredK19** [CommerceRack/backend#61]
#### TICKET SUMMARY #####
ISSUE:  There is no way to merge an order into an existing Customer account in cases where the customer mistakenly enters the wrong email address at checkout.
SERVER:  Naboo
MVC release:  201501.a
EXAMPLE ORDER:  2015-04-36902
EXAMPLE CUSTOMER ACCOUNT:   tricia.mckenzie@luxxery.com [7710275]

NOTES:  Customer entered their email address incorrectly at checkout (tricia.mckenie@luxxery.com, which created new customer account, tricia.mckenie@luxxery.com (CID: 7712583).

Even after deleting the customer account that was created in error, tricia.mckenie@luxxery.com (CID: 7712583), there does not appear to be any way to associate order 2015-04-36902 with the correct customer account, tricia.mckenzie@luxxery.com [7710275]

It would seem that the [Edit Customer] button in the Orders ui should change to the [Assign Customer] button when the originally assigned customer account is deleted.

Checking with dev.

**Comment by michaelchance** [comment]
Fixed with commit https://github.com/CommerceRack/anycommerce/commit/f715cf848d3853068da8d69da72c609537c487aa
