### ISSUE TITLE
Unable to select pricing schedule for Amazon

### ISSUE THREAD

**Issue by LarryM-CR** [CommerceRack/backend#64]
ISSUE: Pricing schedules are not available in dropdown menu to be assigned in Marketplaces > Amazon (bottom of page)

SERVER: bespin5

MVC release: 201501.a

EXAMPLE MERCHANT: tikimaster (tikimaster.com)

STEPS TO REPRODUCE:
Marketplaces > Amazon > Scroll to bottom. Pricing Schedule dropdown menu only has the option of 'none'. Merchant has several pricing schedules setup that should be available for selection.

**Comment by michaelchance** [comment]
I can't replicate this- has it already been fixed?

**Comment by michaelchance** [comment]
Fixed this (and hopefully some other issues as well) with this commit: https://github.com/CommerceRack/anycommerce/commit/231c768dd53a4b62c2d9ffa67f542824bac03782
